apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../runtimes
  - ../../../storagecontainers

generatorOptions:
  disableNameSuffixHash: true

patches:
  # We do not support ClusterServingRuntime, so we need to convert it to ServingRuntime for testing.
  - target:
      kind: ClusterServingRuntime
      group: serving.kserve.io
    patch: |-
      - op: replace
        path: /kind
        value: ServingRuntime
  # Remove the securityContext/runAsUser for the ServingRuntime, it's handled by Openshift.
  - target:
      kind: ServingRuntime
      group: serving.kserve.io
      name: kserve-torchserve
    patch: |-
      - op: remove
        path: /spec/containers/0/securityContext/runAsUser
  - target:
      kind: ServingRuntime
      group: serving.kserve.io
      name: kserve-tritonserver
    patch: |-
      - op: remove
        path: /spec/containers/0/securityContext/runAsUser
  - target:
      kind: ServingRuntime
      group: serving.kserve.io
      name: kserve-tensorflow-serving
    patch: |-
      - op: remove
        path: /spec/containers/0/securityContext/runAsUser

configMapGenerator:
  - envs:
      - ../params-combined.env
    name: kserve-parameters
    behavior: create

replacements:
  - source:
      kind: ConfigMap
      name: kserve-parameters
      fieldPath: data.kserve-storage-initializer
    targets:
      - select:
          kind: ClusterStorageContainer
        fieldPaths:
          - spec.container.image
  - source:
      kind: ConfigMap
      name: kserve-parameters
      fieldPath: data.kserve-sklearn
    targets:
      - select:
          kind: ClusterServingRuntime
          name: kserve-sklearnserver
        fieldPaths:
          - spec.containers.[name=kserve-container].image
