# Copyright 2023 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kserve.configuration import Configuration


class V1beta1CertManagerConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "duration": "V1Duration",
        "enabled": "bool",
        "issuer_group": "str",
        "issuer_kind": "str",
        "issuer_name": "str",
    }

    attribute_map = {
        "duration": "duration",
        "enabled": "enabled",
        "issuer_group": "issuerGroup",
        "issuer_kind": "issuerKind",
        "issuer_name": "issuerName",
    }

    def __init__(
        self,
        duration=None,
        enabled=None,
        issuer_group=None,
        issuer_kind=None,
        issuer_name=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """V1beta1CertManagerConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._duration = None
        self._enabled = None
        self._issuer_group = None
        self._issuer_kind = None
        self._issuer_name = None
        self.discriminator = None

        if duration is not None:
            self.duration = duration
        if enabled is not None:
            self.enabled = enabled
        if issuer_group is not None:
            self.issuer_group = issuer_group
        if issuer_kind is not None:
            self.issuer_kind = issuer_kind
        if issuer_name is not None:
            self.issuer_name = issuer_name

    @property
    def duration(self):
        """Gets the duration of this V1beta1CertManagerConfig.  # noqa: E501


        :return: The duration of this V1beta1CertManagerConfig.  # noqa: E501
        :rtype: V1Duration
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this V1beta1CertManagerConfig.


        :param duration: The duration of this V1beta1CertManagerConfig.  # noqa: E501
        :type: V1Duration
        """

        self._duration = duration

    @property
    def enabled(self):
        """Gets the enabled of this V1beta1CertManagerConfig.  # noqa: E501


        :return: The enabled of this V1beta1CertManagerConfig.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this V1beta1CertManagerConfig.


        :param enabled: The enabled of this V1beta1CertManagerConfig.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def issuer_group(self):
        """Gets the issuer_group of this V1beta1CertManagerConfig.  # noqa: E501


        :return: The issuer_group of this V1beta1CertManagerConfig.  # noqa: E501
        :rtype: str
        """
        return self._issuer_group

    @issuer_group.setter
    def issuer_group(self, issuer_group):
        """Sets the issuer_group of this V1beta1CertManagerConfig.


        :param issuer_group: The issuer_group of this V1beta1CertManagerConfig.  # noqa: E501
        :type: str
        """

        self._issuer_group = issuer_group

    @property
    def issuer_kind(self):
        """Gets the issuer_kind of this V1beta1CertManagerConfig.  # noqa: E501


        :return: The issuer_kind of this V1beta1CertManagerConfig.  # noqa: E501
        :rtype: str
        """
        return self._issuer_kind

    @issuer_kind.setter
    def issuer_kind(self, issuer_kind):
        """Sets the issuer_kind of this V1beta1CertManagerConfig.


        :param issuer_kind: The issuer_kind of this V1beta1CertManagerConfig.  # noqa: E501
        :type: str
        """

        self._issuer_kind = issuer_kind

    @property
    def issuer_name(self):
        """Gets the issuer_name of this V1beta1CertManagerConfig.  # noqa: E501


        :return: The issuer_name of this V1beta1CertManagerConfig.  # noqa: E501
        :rtype: str
        """
        return self._issuer_name

    @issuer_name.setter
    def issuer_name(self, issuer_name):
        """Sets the issuer_name of this V1beta1CertManagerConfig.


        :param issuer_name: The issuer_name of this V1beta1CertManagerConfig.  # noqa: E501
        :type: str
        """

        self._issuer_name = issuer_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict())
                            if hasattr(item[1], "to_dict")
                            else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1beta1CertManagerConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1beta1CertManagerConfig):
            return True

        return self.to_dict() != other.to_dict()
